### PR TITLE
Blank App from scratch

### PR DESCRIPTION
**Pull request by caleybrock**
This branch creates a blank application from scratch.

It uses `django-admin startproject` for the `backend` folder. More info here: https://docs.djangoproject.com/en/2.1/intro/tutorial01/

It uses `npx create-react-app` for the `frontend` folder. More here: https://reactjs.org/docs/create-a-new-react-app.html#create-react-app

I followed this tutorial to get nginx setup: http://felipelinsmachado.com/connecting-django-reactjs-via-nginx-using-docker-containers/

And I followed https://wsvincent.com/django-docker-postgresql/ to get postgresql and docker setup.

I still don't have a readme, but it'd be great if you can give it a try by pulling this branch and running it locally.

All I had to do was `docker-compose up` and I got this at localhost:80
screen shot 2019-01-03 at 12 51 46 pm

### CODE REVIEW

**Comment by MichaelCherry** [comment]
The following occurs when I run it:

$ docker-compose up
Creating network "project-thundercat_default" with the default driver
Creating project-thundercat_frontend_1 ... done
Creating project-thundercat_db_1       ... done
Creating project-thundercat_backend_1  ... done
Creating project-thundercat_nginx_1    ... error

ERROR: for project-thundercat_nginx_1  Cannot start service nginx: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/host_mnt/c/_dev/git/project-thundercat/nginx/nginx-proxy.conf\\\" to rootfs \\\"/var/lib/docker/overlay2/ca6592a3f4dfc65875b2bede37337b53d77b7ee7982da6218062b15d43f99e39/merged\\\" at \\\"/var/lib/docker/overlay2/ca6592a3f4dfc65875b2bede37337b53d77b7ee7982da6218062b15d43f99e39/merged/etc/nginx/conf.d/default.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for nginx  Cannot start service nginx: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/host_mnt/c/_dev/git/project-thundercat/nginx/nginx-proxy.conf\\\" to rootfs \\\"/var/lib/docker/overlay2/ca6592a3f4dfc65875b2bede37337b53d77b7ee7982da6218062b15d43f99e39/merged\\\" at \\\"/var/lib/docker/overlay2/ca6592a3f4dfc65875b2bede37337b53d77b7ee7982da6218062b15d43f99e39/merged/etc/nginx/conf.d/default.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
Encountered errors while bringing up the project.

**Comment by MichaelCherry** [comment]
I am trying to figure out what the underlying cause is.

**Comment by MichaelCherry** [comment]
This may be an issue with my hyper-v or docker configuration? The paths are correct, but it is essentially failing to mount external files onto docker. I well reply with more when I find the cause and will try on my other device in the meantime

**Comment by MichaelCherry** [comment]
On my local machine, I've been having issues with "\r" in "\r\n" being interpreted as part of directory by docker

**Comment by caleybrock** [comment]
We talked about merging this offline. I think it's farther than our original version so we're going to go ahead with it for now.

**Comment by MichaelCherry** [comment]
Sorry, apparently I selected "approve" but did not hit submit

**Comment by rodadmin** [comment]
tried with the start over and got some errors.

**Pull request merged**
