### PR TITLE
Emib tab restructure

### PR DESCRIPTION
**Pull request by MichaelCherry**
Restructure of Emib and tests to include a component with 3 tabs for the test (instructions, background, and inbox) rather than managing 3 individual components within the Emib component.

Addition and update of relevant tests.

Also added "Tab" component, which can hopefully be reused elsewhere

Background Tab:
image

Instructions Tab:
image

Inbox Tab:
image

### CODE REVIEW

**Comment by MichaelCherry** [comment]
image

image

**Comment by MichaelCherry** [comment]
@fnormand01 could you verify that the tab names for Emib.Strings.fr.instructionsTabTitle and backgroundTabTitle are correct? I prefixed both with FR so they still stand out. These are the results of my honed google translating skills, so better to double check

**Comment by MichaelCherry** [comment]
Added some minor tweeks to make the "Next" button and Tab components change the cursor when the mouse hovers over them.

**Comment by fnormand01** [comment]
@MichaelCherry, your translations are good, so you can remove the 'FR' in front of these two words.

**Comment by fnormand01** [comment]
Your changes look good!
Good usage of components and the code is easy to read.

Ran the tests and everything passes and builds successfully.

**Pull request merged**
