### PR TITLE
Set up redux

### PR DESCRIPTION
**Pull request by caleybrock**
# Description

- Add redux to the application
- Create a localization redux module and add a test

## Type of change
- New feature (non-breaking change which adds functionality)

# Testing and Screenshot
There should be no application changes

# Checklist

Applicable for all code changes.

- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new compiler warnings
- [x] My changes generate no new accessibility errors and/or warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have researched WCAG2.1 accessibility standards and met them in this PR (can be navigated using a keyboard)
- [ ] My changes look good on IE 10+, Firefox, and Chrome

### CODE REVIEW

**Comment by fnormand01** [comment]
I had two dependency warnings while building your branch:

image

We should take a look at that before merging this branch to master.

**Comment by MichaelCherry** [comment]
I get the dep warnings (should be an easy fix) and the following in the console:

image


OTHERWISE looks great!

**Comment by MichaelCherry** [comment]
as an aside: apparently the console warning is on master

**Comment by caleybrock** [comment]
I'll take a look that the dependency issues today before merging.

**Comment by caleybrock** [comment]
@fnormand01 the warning should be fixed now.

**Pull request merged**
