### PR TITLE
Docker updates: serve frontend via nginx proxy locally

### PR DESCRIPTION
**Pull request by caleybrock**
Changes from Gabriel to make our local development look like this: 
image

I've confirmed these don't make anything worse on my government computer, and it makes hot-reloading work on my macbook.

----

Here is the fix for Docker, and I’m really starting to think that hot-reloading for windows is simply incompatible because the same configuration works on my linux VM. 

So what I’ve done is I changed the yarn bash script to “yarn start” instead of “yarn build” because yarn build is meant to be production ready so it doesn’t have the hot-reload that you need.

I also fixed the nginx container and I made it work as a reverse proxy pointing to the yarn server.  (This is only for dev environment)

Finally, I changed some settings on the Docker-compose for the frontend container to allow changes. Because before it was copying all the sources into the container, and any modifications were not visible to yarn. Now the sources are directly linked into the container with a volume so the content is always the same.

The last thing to do was really to make it work perfectly on windows with hot-reload, but I will let you work on this. If you want a hint, maybe look into the yarn “webserver” configuration files.

### CODE REVIEW

**Comment by caleybrock** [comment]
While this makes things much better on linux based machines, it does not make things better on Windows, and removes our ability for us to run our "work around" for js changes documented here: https://github.com/code-for-canada/project-thundercat#how-to-run

**Comment by caleybrock** [comment]
Update: I updated an environment variable after reading this trouble shooting document and now hot-reloading works on Windows too!

**Comment by MichaelCherry** [comment]
Works on my local machine. Approving

**Comment by MichaelCherry** [comment]
Hot swapping may not work on windows very well: I remember having a lot of trouble with it for the one dev who insisted on using Windows at my last job. I though the issue was the erlang auto-compiler, but it may have also been a windows issue

**Comment by fnormand01** [comment]
I tested it locally and it worked well. I changed code on App.js and App.test.js and it refreshed perfectly. Seems that the hot-reloading is working well for now.

Hopefully that it will still working well with time.

Approved :-)

**Pull request merged**
