### PR TITLE
[Pre-Test Information] Links of Overview and Tips on Taking the eMIB Fixes/Updates

### PR DESCRIPTION
**Pull request by fnormand01**
# Description

This Pull Request removes the links in Overview and Tip on Taking the eMIB components and replaces them by adding content.

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- Code cleanliness or refactor

## Screenshot

**Overview Component [EN]:**

image

**Overview Component [FR]:**

image

**Tips on Taking the eMIB Component [EN]:**

image

**Tips on Taking the eMIB Component [FR]:**

image

# Testing

Manual steps to reproduce this functionality:

1.  Go to Prototype tab.
2.  Click _Start eMIB Sample Test_.
3.  Take a look at the Overview and Tip on Taking the eMIB components and make sure that the English and French versions are fine, mainly near 'Key Leadership Competencies'.
4.  Take a look at Evaluation component and make sure that the link 'Key Leadership Competencies' works well.

Screenshot of unit tests run passing:

image

# Checklist

Applicable for all code changes.

- [x] My code follows the style guidelines of this project
- [ ] ~~I have commented my code, particularly in hard-to-understand areas~~
- [ ] ~~I have made corresponding changes to the documentation~~
- [x] My changes generate no new compiler warnings
- [x] My changes generate no new accessibility errors and/or warnings
- [ ] ~~I have added tests that prove my fix is effective or that my feature works~~
- [x] New and existing unit tests pass locally with my changes
- [ ] ~~I have researched WCAG2.1 accessibility standards and met them in this PR (can be navigated using a keyboard)~~
- [x] My changes look good on IE 10+, Firefox, and Chrome

### CODE REVIEW

**Comment by MichaelCherry** [comment]
Changes look good in my bowser: one comment: when the page shows up in a different width, I notice this in the French on Tips page:
image

I don't think this was caused by your changes, but may want to fix it in this PR since you're modifying this anyway

**Comment by MichaelCherry** [comment]
One other comment, but this is outside the scope of this PR and probably this Sprint: when clicking the link, the page seems to jump "past" the header (what actually happens is the header jumps to the top of the page; buried under the top nav, etc). This "bug" also is the reason why tabs and side nav are not locked to the top of the page. Just want to note that this is a known issue, but is outside of this PR and Sprint.

**Comment by MichaelCherry** [comment]
ok, skip my first comment. Fixing that causes other issues. Let's worry about that in another PR another time

**Comment by MichaelCherry** [comment]
I think just merge these in, and we'll resolve the spacing issue seperately

**Comment by fnormand01** [comment]
As discussed offline with @MichaelCherry, we'll keep the extra space before the word _compétences_, so the colon in French is not in the next line as below:

**Without added space:**
image

**With added space:**
image

However, when we shrink the page, there is an extra space (2 spaces) between _ces_ and _compétences_ as @MichaelCherry mentioned. But we'll fix all the issues related to colon in French version, since in French there is a space before and after the colon.

**Pull request merged**
