### PR TITLE
Security Patch Django 2.1.5 > 2.1.7

### PR DESCRIPTION
**Pull request by MichaelCherry**
Upgrading Django version 2.1.5 > 2.1.7
Fixes 'Uncontrolled Memory Consumption'

Vulnerability Report Before Patch:
image

Vulnerability Report After Patch:
image

image

### CODE REVIEW

**Comment by caleybrock** [comment]
Do tests still pass?

**Comment by caleybrock** [comment]
On the top right "Edit" button, you should change your base branch to `fix-snyk-local-run` so that this PR only shows new changes, and not ones covered by the other PR?

**Comment by MichaelCherry** [comment]
@caleybrock updated the base and added the screenshot

**Comment by fnormand01** [comment]
Since the changes are now compared to the right branch + you added a screenshot of the tests, as requested by @caleybrock , I'm fine with this version update.

**Pull request merged**
