### PR TITLE
IE Fix: Installed a polyfill to allow app to run on IE

### PR DESCRIPTION
**Pull request by caleybrock**
image
App on IE 11 (PSC default browsers)

### CODE REVIEW

**Comment by fnormand01** [comment]
Is it normal that the 'API' page doesn't work (only in IE)?

**Comment by caleybrock** [comment]
@fnormand01 are you sure you're using `:80/api` ?

**Comment by MichaelCherry** [comment]
when I go to localhost:80/api, it downloads the json, which is accurate. However when I go to localhost:80, I get a blank page. There is a lightning bolt symbol beside the url and on the tab at least. 

image

**Comment by fnormand01** [comment]
It that way, all good with these changes, since it's working as expected on my side.

**Comment by MichaelCherry** [comment]
works for me now.

**Pull request merged**
